name: FGO Login System

on:
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]
  # schedule:
  #   - cron: "30 10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Gettings files from Repo
        uses: actions/checkout@v2

      - name: Install Requeriments
        run: pip install -r requirements.txt

      - name: Execute main script
        run: |
          python3 main.py
        env:
          userIds: ${{ secrets.GAME_USERIDS_1 }}
          authKeys: ${{ secrets.GAME_AUTHKEYS_1 }}
          secretKeys: ${{ secrets.GAME_SECRETKEYS_1 }}
          UserAgent: ${{ secrets.GAME_USERAGENT }}
          fateRegion: ${{ secrets.GAME_REGION }}
          webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
          
      - name: Execute main script
            run: |
              python3 main.py
            env:
              userIds: ${{ secrets.GAME_USERIDS_2 }}
              authKeys: ${{ secrets.GAME_AUTHKEYS_2 }}
              secretKeys: ${{ secrets.GAME_SECRETKEYS_2 }}
              UserAgent: ${{ secrets.GAME_USERAGENT }}
              fateRegion: ${{ secrets.GAME_REGION }}
              webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Execute main script
            run: |
              python3 main.py
            env:
              userIds: ${{ secrets.GAME_USERIDS_3 }}
              authKeys: ${{ secrets.GAME_AUTHKEYS_3 }}
              secretKeys: ${{ secrets.GAME_SECRETKEYS_3 }}
              UserAgent: ${{ secrets.GAME_USERAGENT }}
              fateRegion: ${{ secrets.GAME_REGION }}
              webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Execute main script
            run: |
              python3 main.py
            env:
              userIds: ${{ secrets.GAME_USERIDS_4 }}
              authKeys: ${{ secrets.GAME_AUTHKEYS_4 }}
              secretKeys: ${{ secrets.GAME_SECRETKEYS_4 }}
              UserAgent: ${{ secrets.GAME_USERAGENT }}
              fateRegion: ${{ secrets.GAME_REGION }}
              webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Execute main script
            run: |
              python3 main.py
            env:
              userIds: ${{ secrets.GAME_USERIDS_5 }}
              authKeys: ${{ secrets.GAME_AUTHKEYS_5 }}
              secretKeys: ${{ secrets.GAME_SECRETKEYS_5 }}
              UserAgent: ${{ secrets.GAME_USERAGENT }}
              fateRegion: ${{ secrets.GAME_REGION }}
              webhookDiscord: ${{ secrets.DISCORD_WEBHOOK }}
      
